
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.text.html.CSS;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIVEK
 */

public class NewJFrame extends javax.swing.JFrame {
   
   //Linkedlist list=Linkedlist();
    
     int flag=0,isselect=0,ch1=0,ch2=0,ch3=0,ch4=0,ch5=0,ch6=0,ch7=0,ch8=0,ch9=0;
     String first="",second="";
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jButton1.setText("");  ch1=0;
                  jButton2.setText(""); ch2=0;
                  jButton3.setText(""); ch3=0;
                  jButton4.setText("");ch4=0;
                  jButton5.setText("");ch5=0;
                  jButton7.setText("");ch6=0;
                  jButton6.setText("");ch7=0;
                  jButton8.setText("");ch8=0;
                  jButton9.setText("");ch9=0;
                  jButton1.setBackground(Color.white);
                  jButton2.setBackground(Color.white);
                  jButton3.setBackground(Color.white);
                  jButton4.setBackground(Color.white);
                  jButton5.setBackground(Color.white);
                  jButton6.setBackground(Color.white);
                  jButton7.setBackground(Color.white);
                  jButton8.setBackground(Color.white);
                  jButton9.setBackground(Color.white);
                  
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("TIC TOC TOE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Who wants first chance ?");

        jRadioButton1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText(" X");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("O");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(102, 102, 255));
        jButton12.setText("Play Again");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Turn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(16, 16, 16)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          //int ch=0;
          if(isselect==1){
         if(ch6==0){
        flag++; 
        if(flag%2==1 )
         {
             jLabel3.setText(second);
             jButton6.setText(first);
         }
         else
         {
             jLabel3.setText(first);
             jButton6.setText(second);
         }
        ch6=1;
         String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         
         }}   
          else{
            
             
              //  jLabel2.setForeground(Color.red);
             
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isselect==1){
         if(ch1==0){
        flag++; 
        if(flag%2==1 )
         {
             jButton1.setText(first);
              jLabel3.setText(second);
         }
         else
         {
              jLabel3.setText(first);
             jButton1.setText(second);
         }
        ch1=1;
         String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         }}
        else{
            
             
              //  jLabel2.setForeground(Color.red);
             
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         //int ch=0;
         if(isselect==1){
         if(ch2==0){ 
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton2.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton2.setText(second);
         } 
        ch2++;
        String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         }}
         else{
            
             
              //  jLabel2.setForeground(Color.red);
             
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         //int ch=0;
         if(isselect==1){
         if(ch5==0){ 
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton5.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton5.setText(second);
         }  
          ch5++;
          String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }}
         }
         else{
            
             
             //   jLabel2.setForeground(Color.red);
             
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // int ch=0;
        if(isselect==1){
         if(ch3==0){    
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton3.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton3.setText(second);
         } 
        ch3++;
        String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         }}
        else{
            
             
               // jLabel2.setForeground(Color.red);
             
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
// TODO add your handling code here:
       // jLabel3.setText(first);
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        
       // jLabel3.setText(second);
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // int ch=0;
         if(isselect==1){ 
        if(ch4==0){ 
            
           flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton4.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton4.setText(second);
         } 
        ch4++;
        String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }}
         }
               else{
            
             
               // jLabel2.setForeground(Color.red);
             
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // int ch=0;
        if(isselect==1){
         if(ch7==0){      
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton7.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton7.setText(second);
         } 
        ch7++;
        String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }}
         }
              else{
            
             
               // jLabel2.setForeground(Color.red);
             
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        /// int ch=0;
        if(isselect==1){
         if(ch8==0){  
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton8.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton8.setText(second);
         }    
        ch8++;
        String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         }
         }
else{
            
                         //    jLabel2.setForeground(Color.red);
             
        }
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         //int ch=0;
         if(isselect==1){
         if(ch9==0){   
        flag++; 
        if(flag%2==1 )
         {
              jLabel3.setText(second);
             jButton9.setText(first);
         }
         else
         {
              jLabel3.setText(first);
             jButton9.setText(second);
         }    
        ch9++;
         String result=checkwinner();
         if(result == "")
           {
             int i= checkDraw();
             if(i==1)
             {
                  JOptionPane.showMessageDialog(jPanel1, "\t Match Draw");
             }
           }
         else{
             JOptionPane.showMessageDialog(jPanel1, result+"\t won the match");
         }
         }
         }
          else{
            
             
              //  jLabel2.setForeground(Color.red);
             
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                    flag=0;
        first="X";
      isselect=1;
        second="O";
        jLabel3.setText("X");            
                jLabel2.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                       
                         
                 flag=0; 
                 
                 // jRadioButton1.setSelected(false);
                 // jRadioButton2.setSelected(false);
                 // buttonGroup1.setSelected(buttonGroup1.getSelection(), false); 
                 buttonGroup1.clearSelection();
                 jButton1.setText("");  ch1=0;
                  jButton2.setText(""); ch2=0;
                  jButton3.setText(""); ch3=0;
                  jButton4.setText("");ch4=0;
                  jButton5.setText("");ch5=0;
                  jButton7.setText("");ch6=0;
                  jButton6.setText("");ch7=0;
                  jButton8.setText("");ch8=0;
                  jButton9.setText("");ch9=0;
                  jButton1.setBackground(Color.white);
                  jButton2.setBackground(Color.white);
                  jButton3.setBackground(Color.white);
                  jButton4.setBackground(Color.white);
                  jButton5.setBackground(Color.white);
                  jButton6.setBackground(Color.white);
                  jButton7.setBackground(Color.white);
                  jButton8.setBackground(Color.white);
                  jButton9.setBackground(Color.white);
                   isselect=0;  
                   jLabel3.setText("");
// jButton1.setText("");
                //  jRadioButton1.getDisabledIcon();
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
         flag=0;
        second="X";
        first="O";
        isselect=1;     
        jLabel3.setText("O"); 
         
             jLabel2.setForeground(Color.black);      
         
                              
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
              jLabel2.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
         if(isselect==0){
             jLabel2.setForeground(Color.red);      
         }    
               
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
                  if(isselect==0){
             jLabel2.setForeground(Color.red);      
         }    
                      
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
          if(isselect==0){
             jLabel2.setForeground(Color.black);      
         }    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
            if(isselect==0){
             jLabel2.setForeground(Color.red);      
         }    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

    /**
     * @param args the command line arguments
     */
    
 String checkwinner()
   {
       if(jButton1.getText()==jButton2.getText() && jButton2.getText()==jButton3.getText() && jButton1.getText()!="")
       {
           jButton1.setBackground(Color.red);
           jButton2.setBackground(Color.red);
           jButton3.setBackground(Color.red);
          System.out.println("  Rule No 1");
           return jButton1.getText();
       }
       if(jButton4.getText()==jButton5.getText() && jButton5.getText()==jButton6.getText() &&jButton4.getText()!="")
       {
            jButton4.setBackground(Color.red);
           jButton5.setBackground(Color.red);
           jButton6.setBackground(Color.red);
            System.out.println("  Rule No 2");
           return jButton4.getText();
       }
       if(jButton9.getText()==jButton8.getText() && jButton8.getText()==jButton7.getText() && jButton9.getText()!="")
       {
            jButton7.setBackground(Color.red);
           jButton8.setBackground(Color.red);
           jButton9.setBackground(Color.red);
            System.out.println("  Rule No 3");
           return jButton9.getText();
       }
          if(jButton1.getText()==jButton4.getText() && jButton4.getText()==jButton7.getText() && jButton7.getText()!="" )
       {
            jButton1.setBackground(Color.red);
           jButton4.setBackground(Color.red);
           jButton7.setBackground(Color.red);
            System.out.println("  Rule No 4");
           return jButton1.getText();
       }
       if(jButton2.getText()==jButton5.getText() && jButton2.getText()==jButton8.getText() && jButton2.getText()!="")
       {
            jButton5.setBackground(Color.red);
           jButton2.setBackground(Color.red);
           jButton8.setBackground(Color.red);
            System.out.println("  Rule No 5");
          return jButton2.getText();
       }
        if(jButton3.getText()==jButton6.getText() && jButton6.getText()==jButton9.getText()&& jButton3.getText()!="" )
       {
            jButton6.setBackground(Color.red);
           jButton9.setBackground(Color.red);
           jButton3.setBackground(Color.red);
            System.out.println("  Rule No 6");
          return jButton3.getText();
       }
             if(jButton1.getText()==jButton5.getText() && jButton5.getText()==jButton9.getText() && jButton1.getText()!="" )
       {
            jButton1.setBackground(Color.red);
           jButton5.setBackground(Color.red);
           jButton9.setBackground(Color.red);
            System.out.println("  Rule No 7");
           return jButton1.getText();
       }                        
             if(jButton3.getText()==jButton5.getText() && jButton5.getText()==jButton7.getText() && jButton3.getText()!="" )
       {
            jButton5.setBackground(Color.red);
           jButton7.setBackground(Color.red);
           jButton3.setBackground(Color.red);
            System.out.println("  Rule No 8");
           return jButton3.getText();
       }                   
    return "";
   }
 int checkDraw()
 {
     if(jButton1.getText()!="" && jButton3.getText()!="" && jButton4.getText()!="" && jButton5.getText()!="" && jButton7.getText()!="" && jButton6.getText()!="" && jButton8.getText()!="" && jButton9.getText()!="" )
     {
           return 1;      
     }
     return 0;
 }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
  
}